version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456789
      DB_NAME: blogging_system
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: blogging_system
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
